
language: python

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
install:
  - pip install ".[test]"

script:
  - pip install -e .
  - python -m doctest -v README.md
  - py.test --cov=convergence tests

env:
  - CODECOV_TOKEN="0a761bdf-6546-411f-88c8-dac96fc73df0"

after_success:
  - '[ $TRAVIS_PYTHON_VERSION == "2.7" ] && codecov'
