
language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
install:
  - pip install ".[test]"

script:
  - pip install -e .
  - py.test --cov=convergence tests

env:
  - CODECOV_TOKEN="87c24ef5-b1eb-4833-87b4-34706d9e1e8d"

after_success:
  - codecov
