name: Documentation
on: [push, pull_request]
jobs:
  doctest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          conda info
      - name: Install package
        run: |
          pip install --no-deps .
      - name: Run tests
        run: |
          python -m doctest -v README.md
  status:
    name: Documentation
    runs-on: ubuntu-latest
    needs: doctest
    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Documentation",
            "state": "success",
            "description": "Documentation deployed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
