name: Semantic Release

on: [push]

jobs:
  release:
    name: Publish the package
    runs-on: ubuntu-latest
    concurrency: release
    if: |
        github.repository == 'Data-Only-Greater/convergence' &&
        github.event.pusher.name != 'actions-user'
    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        running-workflow-name: 'Publish the package'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.ADMIN_TOKEN }}
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.ADMIN_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
