name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.released }}
    permissions:
      id-token: write
      contents: write
    if: github.repository == 'Data-Only-Greater/convergence'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.ADMIN_TOKEN }}
    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        running-workflow-name: 'Create release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
      if: env.GIT_COMMIT_COMMITTER_NAME != 'github-actions'
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.ADMIN_TOKEN }}

  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.released == 'true'
    permissions:
      id-token: write
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.ADMIN_TOKEN }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/upload-to-gh-release@main
      with:
        github_token: ${{ secrets.ADMIN_TOKEN }}
