name: Unit Tests
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10']
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          conda info
      - name: Install package
        run: |
          pip install --no-deps -e .
      - name: Run tests
        run: |
          conda install -y mock pytest pytest-cov pytest-mock
          pytest --cov=convergence --cov-report xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
            fail_ci_if_error: true
            token: ${{ secrets.CODECOV_TOKEN }}
  status:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Unit Tests",
            "state": "success",
            "description": "Unit tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
